#pragma config(Sensor, S1,     touchSensor,    sensorEV3_Touch)
#pragma config(Sensor, S2,     sonarSensor,    sensorEV3_Ultrasonic)
#pragma config(Sensor, S3,     gyroSensor,     sensorEV3_Gyro)
#pragma config(Sensor, S4,     colorSensor,    sensorEV3_Color)
#pragma config(Motor,  motorA,          armMotor,      tmotorEV3_Large, PIDControl, encoder)
#pragma config(Motor,  motorB,          leftMotor,     tmotorEV3_Large, PIDControl, driveLeft, encoder)
#pragma config(Motor,  motorC,          rightMotor,    tmotorEV3_Large, PIDControl, driveRight, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
task main()
{
    playSound(soundBeepBeep);
    sleep(3000);
    playSound(soundFastUpwardTones);
    sleep(3000);

    while(getTouchValue(touchSensor) == 0){};
    setMotorSpeed(leftMotor, 50);
    setMotorSpeed(rightMotor, 50);
    sleep(2000);

    setMotorSpeed(leftMotor,50);
    setMotorSpeed(rightMotor,0);
    sleep(3000);

    setMotorSpeed(leftMotor,0);
    setMotorSpeed(rightMotor,0);

    int col;
    while(1) {
        col = getColorReflected(colorSensor);
        playImmediateTone(col * 10,50);
        sleep(500);
    }
}
